from unittest import result
from pydantic import BaseModel, Field
from typing import Optional
from langchain_openai import ChatOpenAI
from langchain.agents import create_agent
from langchain.agents.structured_output import ProviderStrategy
from langchain.agents.middleware import FilesystemFileSearchMiddleware
import uuid
import json
import base64
import sys
import os
import importlib.util
import re

# Importing schema
from automatic_program_engineering.blueprints.BlueprintSchema import BlueprintSchema

# Importing candidate model.
from automatic_program_engineering.autogenerated_files.AutogeneratedCandidateSchema import CandidateSchema

# Define project paths
input_file_path = "D:/DOCUMENTS/self_study/Agents/langchain_learning/automatic_program_engineering/assets/input_file/"
json_desired_output_path = "D:/DOCUMENTS/self_study/Agents/langchain_learning/automatic_program_engineering/desired_output/output_auto_chubb.json"
blueprint_schema_path = "D:/DOCUMENTS/self_study/Agents/langchain_learning/automatic_program_engineering/blueprints/BlueprintSchema.py"
auto_generated_prompt = "D:/DOCUMENTS/self_study/Agents/langchain_learning/automatic_program_engineering/autogenerated_files/AutogeneratedPrompt.json"
auto_generated_candidate_schema = "D:/DOCUMENTS/self_study/Agents/langchain_learning/automatic_program_engineering/autogenerated_files/AutogeneratedCandidateSchema.py"

# autogenerated_file_destination_path = "D:/DOCUMENTS/self_study/Agents/langchain_learning/automatic_program_engineering/autogenerated_prompts"


# Define prompt for automatic program engineering (APE).
template_generator_prompt = """
    Eres un experto prompt engineer especializado en extraer datos estructurados de documentos no estructurados.

    Recibirás como entrada:
        - El archivo del cual se extraerá la información.
        - La información deseada en el esquema de salida.

    Instrucciónes:
    1. Analiza los campos de la salida estructurada.
    2. En el JSON que se te proporciona, localiza el output del campo correspondiente.
    3. Una vez localizado, encuentra en que parte del documento está esa información.
    4. Genera una plantilla de prompt detallada para cada campo, enfocándote en patrones y diseño del documento.
    5. Evita dar ejemplos de salidas en la descripción.
"""

template_generator_prompt = f"""
    Eres un experto en extraer datos estructurados de documentos no estructurados.

    Recibirás como entrada:
    - El archivo del cual se extraerá la información.
    - La información deseada en el esquema de salida.

    # Tu tarea es generar una plantilla de prompt para cada campo de la salida estructurada.

    > Enfócate mas en los patrones y diseño del documento mas que en obtener los valores específicos.
    > Esta descripción será de mucha ayuda para que en proximas llamadas sepas donde esta "localizada" la información correctamente.

    Tomate tu tiempo para dar una descripción detallada para cada campo en el esquema de salida.

    # Evita dar ejemplo de salidas en la descripción.
"""

template_validator_prompt =f"""
    Eres un experto en extraer datos estructurados de documentos no estructurados.
    Recibirás como entrada:
    - El archivo del cual se extraerá la información.
    - La información deseada en el esquema de salida.
"""



# Define the data model to create the prompts.
class GeneralInvoiceInformation(BaseModel):
    poliza: str                 = Field(default="")
    inicioPeriodoVigencia: str   = Field(default="")
    finalPeriodoVigencia: str    = Field(default="")
    aseguradora: str            = Field(default="")
    ramo: str                   = Field(default="")
    subRamo: str                = Field(default="")
    cobertura: str              = Field(description="")
    formaDePago: str           = Field(default="")
    primaNeta: int             = Field(default="")
    primerPago: int            = Field(default="")
    pagoPosterior: int     = Field(default="")
    descuento: int         = Field(default="")
    iva: int               = Field(default="")
    tasaFinanciamiento: int = Field(default="")
    derechoPoliza: str     = Field(default="")
    total: int             = Field(default="")
    cargoPorFinanciamiento: int = Field(default="")
    rfcAsegurado: str     = Field(default="")
    nombreAsegurado: str  = Field(default="")
    numeroSerie: str      = Field(default="")
    modelo: str           = Field(default="")
    numeroPlacas: str     = Field(default="")
    adaptaciones: str     = Field(default="")
    version: str          = Field(default="")
    beneficiarioPreferente: str = Field(default="")

# Auxiliar functions
def safe_description(val):
    # Ensure the description is a string and escape problematic quotes
    if not isinstance(val, str):
        val = str(val)
    return val.replace('"', "'")

class LangChainMessage(BaseModel):
    role: str
    content: str

# Sub-processes 
def auto_generate_prompt(messages: list[LangChainMessage]) -> dict:
    prompt_template_dict = {}

    # Selecting the model
    llm = ChatOpenAI(
        model="gpt-5.1-2025-11-13",
    )

    # Create agent 
    agent_template_generator = create_agent(
        model=llm,
        tools=[],
        response_format=ProviderStrategy(GeneralInvoiceInformation),
        middleware=[
            FilesystemFileSearchMiddleware(
                root_path="automatic_program_engineering/input_files/first_test/"
                # max_files=1,
            )
        ],
        system_prompt=template_generator_prompt,
    )

    # Desired output data. 
    with open(json_desired_output, "r", encoding="utf-8") as f:
        desired_output = json.load(f)


    # Invoke agent to get prompt template.
    messages.append(
        LangChainMessage(
            role="developer",
            content=f"""
                Aquí está la información en output_auto_chubb.json
                {desired_output}
            """
        )
    )

    result = agent_template_generator.invoke(
        {
            "messages": [
                {
                    "type": "developer",
                    "content": f"""
                        Aquí está la información en output_auto_chubb.json
                        {desired_output}
                    """
                }
            ]
        }
    )

    prompt_template = result.get("structured_response")
    

    # If you want it as a dictionary:
    if prompt_template:
        prompt_template_dict = prompt_template.dict()
    else:
        print("No structured_response found in result.")

    return prompt_template_dict

# Main process
def execute_ape_process():
    messages:list[LangChainMessage] = []

    for i in range(3):
        print(f"Starting iteration {i + 1}...\n")

        print("Starting Automatic Program Engineering (APE) process...\n")
        prompt_template_dict = auto_generate_prompt(messages)

        print("Using the auto prompt template to extract information.\n")
        information_extracted = extract_information_from_prompt(prompt_template_dict)

        # Use the actual model output from result_validation
        with open(json_desired_output, "r", encoding="utf-8") as f:
            reference_output = json.load(f)

        print("Assess accuracy of the template.\n")
        comparision = assess_the_extraction_accuracy(information_extracted, reference_output)
        
        messages.append(
            LangChainMessage(
                role="system",
                content=f"Iteración pasada: {comparision}"
            )
        )


        store_prompt_template(prompt_template_dict, comparision["overall_accuracy"])

# execute_ape_process()


# Sub-processes
def generate_prompt_from_blueprint(prompt_generator, source_file_path, desired_output_file_path, messages: list[LangChainMessage]) -> dict:
    prompt_template_dict = {}

    # Selecting the model
    llm = ChatOpenAI(model="gpt-5.1-2025-11-13")

    # Create agent 
    agent_template_generator = create_agent(
        model=llm,
        tools=[],
        response_format=ProviderStrategy(BlueprintSchema),
        middleware=[
            FilesystemFileSearchMiddleware(
                root_path=source_file_path
                # max_files=1,
            )
        ],
        system_prompt=prompt_generator,
    )

    # Desired output data. 
    with open(desired_output_file_path, "r", encoding="utf-8") as f:
        desired_output = json.load(f)

    # Invoke agent to get prompt template.
    print("Invoke agent for prompt generation")
    messages.append(
        LangChainMessage(
            role="developer",
            content=f"""
                Aquí está la información:
                {desired_output}
            """
        )
    )

    result = agent_template_generator.invoke(
        {
            "messages": [
                {
                    "type": "developer",
                    "content": f"""
                        Aquí está la información en output_auto_chubb.json
                        {desired_output}
                    """
                }
            ]
        }
    )

    prompt_template = result.get("structured_response")
    
    # If you want it as a dictionary:
    if prompt_template:
        prompt_template_dict = prompt_template.dict()
    else:
        print("No structured_response found in result.")

    return prompt_template_dict

def store_json_generated_prompt(json_prompt: dict, file_destination_path: str) -> str:
    # Write the JSON prompt as a Python file with a variable assignment
    py_file_path = file_destination_path
    os.makedirs(os.path.dirname(py_file_path), exist_ok=True)
    with open(py_file_path, "w", encoding="utf-8") as f:
        json.dump(json_prompt, f, ensure_ascii=False, indent=2)
    print(f"Generated prompt Python file saved to {py_file_path}")
    return py_file_path

def generate_candidate_schema_model(autogenerated_prompt_json_file_path: str, destination_path: str):
    """
    Generate a CandidateSchema class from the autogenerated prompt JSON file,
    using the field descriptions from the JSON.
    """
    # Read the prompt descriptions from the JSON file
    with open(autogenerated_prompt_json_file_path, "r", encoding="utf-8") as f:
        prompt_dict = json.load(f)

    candidate_class_name = "CandidateSchema"
    lines = ["from pydantic import BaseModel, Field\n\n"]
    lines.append(f"class {candidate_class_name}(BaseModel):\n")
    for field, desc in prompt_dict.items():
        # Escape double quotes in description
        desc = str(desc).replace('"', "'")
        lines.append(f"    {field}: str|None = Field(default=None, description=\"{safe_description(desc)}\")\n")

    # Write the candidate schema to the destination path
    os.makedirs(os.path.dirname(destination_path), exist_ok=True)
    with open(destination_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"Candidate schema saved to {destination_path}")

def extract_information_from_prompt(prompt_template_dict: dict, input_file: dict) -> dict:
    # Selecting the model
    llm = ChatOpenAI(
        model="gpt-4.1",
    )

    agent_template_validator = create_agent(
        model=llm,
        tools=[],
        response_format=ProviderStrategy(CandidateSchema),
        middleware=[
            FilesystemFileSearchMiddleware(
                root_path="automatic_program_engineering/input_files/first_test/"
                # max_files=1,
            )
        ],
        system_prompt=template_validator_prompt,
    )

    result_validation = agent_template_validator.invoke({
        "messages": [
            {
                "type": "developer",
                "content": f"""
                    Extrae la información de acuerdo con tu prompt.
                """
            }
        ]
    })

    model_output = result_validation.get('structured_response')

    if model_output:
        model_output_dict = model_output.dict() if hasattr(model_output, 'dict') else model_output
    else:
        print("No structured_response found in result_validation.")
        model_output_dict = {}
    
    return model_output_dict

def assess_the_extraction_accuracy(information_extracted: dict, reference_output: dict) -> dict:
    # Compare each field
    comparison = {}

    for key in reference_output:
        ref_val = reference_output[key]
        model_val = information_extracted.get(key, None)
        comparison[key] = {
            "expected": ref_val,
            "actual": model_val,
            "match": ref_val == model_val
        }

    print("\nField-by-field comparison:")
    for k, v in comparison.items():
        print(f"{k}: expected={v['expected']} | actual={v['actual']} | match={v['match']}")

    # Calculate accuracy
    total = len(comparison)
    correct = sum(1 for v in comparison.values() if v["match"])
    accuracy = correct / total if total > 0 else 0.0
    print(f"\nOverall accuracy: {accuracy*100:.2f}%")
    
    comparison['overall_accuracy'] = accuracy

    return comparison

def store_prompt_template(prompt_template_dict: dict, accuracy: dict) -> str:
    prompt_template_dir = "automatic_program_engineering/prompt_template"
    os.makedirs(prompt_template_dir, exist_ok=True)

    # Save template dict and accuracy
    prompt_template_to_store = {
        "prompt_template": prompt_template_dict,
        "accuracy": accuracy
    }

    unique_id = str(uuid.uuid4())
    prompt_template_path = os.path.join(prompt_template_dir, f"prompt_template_{unique_id}.json")
    with open(prompt_template_path, "w", encoding="utf-8") as f:
        json.dump(prompt_template_to_store, f, ensure_ascii=False, indent=2)
    print(f"\nPrompt template and accuracy saved to {prompt_template_path}")


def main():
    # Desired output data.
    json_desired_output = {}

    with open(json_desired_output_path, "r", encoding="utf-8") as f:
        json_desired_output = json.load(f)

    messages:list[LangChainMessage] = []

    for i in range(3):

        # Generate prompt from blueprint. Contains the description of how to locate each field in the file.
        # print("Generating prompt from blueprint...")
        # json_prompt:dict = generate_prompt_from_blueprint(template_generator_prompt, input_file_path, json_desired_output_path, [])

        # # Store json_prompt in a file
        # print("Storing generated prompt...")
        # autogenerated_prompt = store_json_generated_prompt(json_prompt, auto_generated_prompt)

        # print("Generating candidate schema model...")
        # generate_candidate_schema_model(auto_generated_prompt, auto_generated_candidate_schema)

        print("Using candidate schema to extract information...")
        extracted_info = extract_information_from_prompt(auto_generated_prompt, input_file_path)
        
        assess_the_extraction_accuracy(extracted_info, json_desired_output)

main()
