from pydantic import BaseModel, Field

class BlueprintSchema(BaseModel):
    poliza: str|None = Field(default=None, description="")
    inicioPeriodoVigencia: str|None = Field(default=None, description="")
    finalPeriodoVigencia: str|None = Field(default=None, description="")
    aseguradora: str|None = Field(default=None, description="")
    ramo: str|None = Field(default=None, description="")
    subRamo: str|None = Field(default=None, description="")
    cobertura: str|None = Field(default=None, description="")
    formaDePago: str|None = Field(default=None, description="")
    primaNeta: str|None = Field(default=None, description="")
    primerPago: str|None = Field(default=None, description="")
    pagoPosterior: str|None = Field(default=None, description="")
    descuento: str|None = Field(default=None, description="")
    iva: str|None = Field(default=None, description="")
    tasaFinanciamiento: str|None = Field(default=None, description="")
    derechoPoliza: str|None = Field(default=None, description="")
    total: str|None = Field(default=None, description="")
    cargoPorFinanciamiento: str|None = Field(default=None, description="")
    rfcAsegurado: str|None = Field(default=None, description="")
    nombreAsegurado: str|None = Field(default=None, description="")
    numeroSerie: str|None = Field(default=None, description="")
    modelo: str|None = Field(default=None, description="")
    numeroPlacas: str|None = Field(default=None, description="")
    adaptaciones: str|None = Field(default=None, description="")
    version: str|None = Field(default=None, description="")
    beneficiarioPreferente: str|None = Field(default=None, description="")
